// Generated by scripts/fetch-libertadores-rosters.mjs. Do not edit by hand.
// Player identity snapshot: CONMEBOL-2026-09-01. Emifoot ratings are derived at game creation.
export const LIBERTADORES_ROSTER_SNAPSHOT_ID = "CONMEBOL-2026-09-01" as const
export const RAW_LIBERTADORES_ROSTERS = [
  {
    "id": "conmebol-river-plate",
    "source": "ESPN arg.1 roster, 2026-09-01",
    "players": [
      {
        "sourceId": "espn-361402",
        "name": "Santiago Beltrán",
        "position": "G",
        "age": 21,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-254324",
        "name": "Ezequiel Centuríon",
        "position": "G",
        "age": 29,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-219086",
        "name": "Lucas Martínez Quarta",
        "position": "D",
        "age": 30,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-119289",
        "name": "Nicolás Otamendi",
        "position": "D",
        "age": 38,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-228262",
        "name": "Gonzalo Montiel",
        "position": "D",
        "age": 29,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-268525",
        "name": "Francisco Ortega",
        "position": "D",
        "age": 27,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-208642",
        "name": "Giovanni González",
        "position": "D",
        "age": 31,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-382912",
        "name": "Lautaruo Rivero",
        "position": "D",
        "age": 22,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-280381",
        "name": "Lucas Beltrán",
        "position": "M",
        "age": 25,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-307332",
        "name": "Tomás Galván",
        "position": "M",
        "age": 26,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-272319",
        "name": "Fausto Vera",
        "position": "M",
        "age": 26,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-286406",
        "name": "Aníbal Moreno",
        "position": "M",
        "age": 27,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-199775",
        "name": "Mauro Arambarri",
        "position": "M",
        "age": 30,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-277208",
        "name": "Thiago Almada",
        "position": "M",
        "age": 25,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-195681",
        "name": "Ángel Correa",
        "position": "A",
        "age": 31,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-414769",
        "name": "Joaquin Freitas",
        "position": "A",
        "age": 20,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-197052",
        "name": "Rafael Borré",
        "position": "A",
        "age": 30,
        "nationality": "COL"
      },
      {
        "sourceId": "espn-421410",
        "name": "Lautaro Pereyra",
        "position": "A",
        "age": 18,
        "nationality": "ARG"
      }
    ]
  },
  {
    "id": "conmebol-boca-juniors",
    "source": "ESPN arg.1 roster, 2026-09-01",
    "players": [
      {
        "sourceId": "espn-195663",
        "name": "Agustín Marchesín",
        "position": "G",
        "age": 38,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-166323",
        "name": "Álvaro Montero",
        "position": "G",
        "age": 31,
        "nationality": "COL"
      },
      {
        "sourceId": "espn-290542",
        "name": "Lautaro Blanco",
        "position": "D",
        "age": 27,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-341457",
        "name": "Lautaro Di Lollo",
        "position": "D",
        "age": 22,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-286902",
        "name": "Ayrton Costa",
        "position": "D",
        "age": 27,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-371485",
        "name": "Dylan Gorosito",
        "position": "D",
        "age": 20,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-338991",
        "name": "Leandro Lozano",
        "position": "D",
        "age": 27,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-303633",
        "name": "Marco Pellegrino",
        "position": "D",
        "age": 24,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-286516",
        "name": "Alan Velasco",
        "position": "M",
        "age": 24,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-233734",
        "name": "Santiago Ascacibar",
        "position": "M",
        "age": 29,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-382978",
        "name": "Milton Delgado",
        "position": "M",
        "age": 21,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-400359",
        "name": "Tomás Aranda",
        "position": "M",
        "age": 19,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-153115",
        "name": "Leandro Paredes",
        "position": "M",
        "age": 32,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-104506",
        "name": "Camilo Rey",
        "position": "M",
        "age": 20,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-400360",
        "name": "Leonel Flores",
        "position": "A",
        "age": 18,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-260812",
        "name": "Miguel Merentiel",
        "position": "A",
        "age": 30,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-141790",
        "name": "Sebastián Villa",
        "position": "A",
        "age": 30,
        "nationality": "COL"
      },
      {
        "sourceId": "espn-171771",
        "name": "Enner Valencia",
        "position": "A",
        "age": 36,
        "nationality": "ECU"
      }
    ]
  },
  {
    "id": "conmebol-racing",
    "source": "ESPN arg.1 roster, 2026-09-01",
    "players": [
      {
        "sourceId": "espn-233910",
        "name": "Facundo Cambeses",
        "position": "G",
        "age": 29,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-339802",
        "name": "Francisco Gómez",
        "position": "G",
        "age": 22,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-311747",
        "name": "Ezequiel Cannavo",
        "position": "D",
        "age": 24,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-129426",
        "name": "Marcos Rojo",
        "position": "D",
        "age": 36,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-268534",
        "name": "Nazareno Colombo",
        "position": "D",
        "age": 27,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-361553",
        "name": "Gonzalo Escudero",
        "position": "D",
        "age": 19,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-400994",
        "name": "Mateo Martínez",
        "position": "D",
        "age": 18,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-199790",
        "name": "Pacha Espino",
        "position": "D",
        "age": 34,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-285696",
        "name": "Diego Ortegoza",
        "position": "M",
        "age": 29,
        "nationality": "CHI"
      },
      {
        "sourceId": "espn-276283",
        "name": "Matko Miljevic",
        "position": "M",
        "age": 25,
        "nationality": "USA"
      },
      {
        "sourceId": "espn-317430",
        "name": "Ignacio Agustin Rodríguez",
        "position": "M",
        "age": 24,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-70303",
        "name": "Alejandro Tello",
        "position": "M",
        "age": 18,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-195645",
        "name": "Matías Kranevitter",
        "position": "M",
        "age": 33,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-241988",
        "name": "Matías Zaracho",
        "position": "M",
        "age": 28,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-228388",
        "name": "Tomás Conechny",
        "position": "A",
        "age": 28,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-346184",
        "name": "Elías Torres",
        "position": "A",
        "age": 25,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-292041",
        "name": "Lautaro Díaz",
        "position": "A",
        "age": 28,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-337972",
        "name": "Valentin Carboni",
        "position": "A",
        "age": 21,
        "nationality": "ARG"
      }
    ]
  },
  {
    "id": "conmebol-independiente",
    "source": "ESPN arg.1 roster, 2026-09-01",
    "players": [
      {
        "sourceId": "espn-154747",
        "name": "Rodrigo Rey",
        "position": "G",
        "age": 35,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-276303",
        "name": "Joaquín Blázquez",
        "position": "G",
        "age": 25,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-310003",
        "name": "Facundo Zabala",
        "position": "D",
        "age": 27,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-297052",
        "name": "Kevin Lomónaco",
        "position": "D",
        "age": 24,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-164756",
        "name": "Santiago Arias",
        "position": "D",
        "age": 34,
        "nationality": "COL"
      },
      {
        "sourceId": "espn-293381",
        "name": "Juan Fedorco",
        "position": "D",
        "age": 25,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-187848",
        "name": "Leonardo Godoy",
        "position": "D",
        "age": 31,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-3112633",
        "name": "Juan Migue Arrayago",
        "position": "D",
        "age": 23,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-127893",
        "name": "Iván Marcone",
        "position": "M",
        "age": 36,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-317219",
        "name": "Mateo Pérez",
        "position": "M",
        "age": 20,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-384667",
        "name": "Lautaro Millán",
        "position": "M",
        "age": 21,
        "nationality": "CHI"
      },
      {
        "sourceId": "espn-414360",
        "name": "Josias Palais",
        "position": "M",
        "age": 20,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-158304",
        "name": "Luciano Cabral",
        "position": "M",
        "age": 31,
        "nationality": "CHI"
      },
      {
        "sourceId": "espn-361260",
        "name": "Ruben Martinez",
        "position": "M",
        "age": 22,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-359827",
        "name": "Matías Abaldo",
        "position": "A",
        "age": 22,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-208650",
        "name": "Maximiliano Gutiérrez",
        "position": "A",
        "age": 22,
        "nationality": "CHI"
      },
      {
        "sourceId": "espn-172539",
        "name": "Maximiliano Meza",
        "position": "A",
        "age": 33,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-307331",
        "name": "Santiago Montiel",
        "position": "A",
        "age": 25,
        "nationality": "ARG"
      }
    ]
  },
  {
    "id": "conmebol-nacional",
    "source": "ESPN uru.1 roster, 2026-09-01",
    "players": [
      {
        "sourceId": "espn-199653",
        "name": "Alexis Martín Arias",
        "position": "G",
        "age": 34,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-307467",
        "name": "Ignacio Suárez",
        "position": "G",
        "age": 24,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-254033",
        "name": "Agustin Rogel",
        "position": "D",
        "age": 28,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-3103449",
        "name": "Benjamín Núñez Barolin",
        "position": "D",
        "age": 23,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-220130",
        "name": "Camilo Cándido",
        "position": "D",
        "age": 31,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-285807",
        "name": "Emiliano Ancheta",
        "position": "D",
        "age": 27,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-159195",
        "name": "Francisco Calvo",
        "position": "D",
        "age": 34,
        "nationality": "CRC"
      },
      {
        "sourceId": "espn-302209",
        "name": "Gastón Martirena",
        "position": "D",
        "age": 26,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-402825",
        "name": "Agustín Dos Santos",
        "position": "M",
        "age": 18,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-144267",
        "name": "Bruno Zuculini",
        "position": "M",
        "age": 33,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-402584",
        "name": "Juan García",
        "position": "M",
        "age": 20,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-402590",
        "name": "Kevin Martínez",
        "position": "M",
        "age": 18,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-208659",
        "name": "Lucas Rodríguez",
        "position": "M",
        "age": 33,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-333305",
        "name": "Luciano Boggio",
        "position": "M",
        "age": 27,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-218651",
        "name": "Juan Santos",
        "position": "A",
        "age": 23,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-67183",
        "name": "Maxi Gómez",
        "position": "A",
        "age": 30,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-334992",
        "name": "Maximiliano Silvera",
        "position": "A",
        "age": 28,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-402589",
        "name": "Pavel Núñez",
        "position": "A",
        "age": 20,
        "nationality": "URU"
      }
    ]
  },
  {
    "id": "conmebol-penarol",
    "source": "ESPN uru.1 roster, 2026-09-01",
    "players": [
      {
        "sourceId": "espn-383124",
        "name": "Luis Díaz",
        "position": "G",
        "age": 20,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-215994",
        "name": "Sebastian Britos Rodriguez",
        "position": "G",
        "age": 38,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-338977",
        "name": "Andrés Madruga",
        "position": "D",
        "age": 22,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-412228",
        "name": "Brian Barboza",
        "position": "D",
        "age": 18,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-178116",
        "name": "Diego Laxalt",
        "position": "D",
        "age": 33,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-402484",
        "name": "Facundo Álvez",
        "position": "D",
        "age": 19,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-128422",
        "name": "Franco Romero",
        "position": "D",
        "age": 31,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-383119",
        "name": "Ignacio Alegre",
        "position": "D",
        "age": 20,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-356347",
        "name": "Eduardo Darias",
        "position": "M",
        "age": 28,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-207238",
        "name": "Eric Remedi",
        "position": "M",
        "age": 31,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-288186",
        "name": "Franco González",
        "position": "M",
        "age": 22,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-383129",
        "name": "Germán Barbas",
        "position": "M",
        "age": 18,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-284858",
        "name": "Jesús Trindade",
        "position": "M",
        "age": 33,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-402483",
        "name": "Julio Daguer",
        "position": "M",
        "age": 18,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-131430",
        "name": "Abel Hernández",
        "position": "A",
        "age": 36,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-402490",
        "name": "Brandon Álvarez",
        "position": "A",
        "age": 18,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-412315",
        "name": "Cristian Jaime",
        "position": "A",
        "age": 20,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-287029",
        "name": "Douglas Arezo",
        "position": "A",
        "age": 23,
        "nationality": "URU"
      }
    ]
  },
  {
    "id": "conmebol-olimpia",
    "source": "ESPN par.1 roster, 2026-09-01",
    "players": [
      {
        "sourceId": "espn-190375",
        "name": "Gastón Olveira",
        "position": "G",
        "age": 33,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-255383",
        "name": "Carlos Lentinelly",
        "position": "G",
        "age": 29,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-363475",
        "name": "Alan Rodríguez",
        "position": "D",
        "age": 26,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-215564",
        "name": "Juan Alfaro",
        "position": "D",
        "age": 26,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-285755",
        "name": "Mateo Gamarra",
        "position": "D",
        "age": 25,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-191639",
        "name": "Raúl Cáceres",
        "position": "D",
        "age": 34,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-307315",
        "name": "Gustavo Vargas",
        "position": "D",
        "age": 24,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-159470",
        "name": "Tim Payne",
        "position": "D",
        "age": 32,
        "nationality": "NZL"
      },
      {
        "sourceId": "espn-307628",
        "name": "Bernardo Benitez",
        "position": "M",
        "age": 23,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-402631",
        "name": "Eduardo Delmás",
        "position": "M",
        "age": 19,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-251986",
        "name": "Richard Sánchez",
        "position": "M",
        "age": 30,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-346629",
        "name": "Rubén Lezcano",
        "position": "M",
        "age": 22,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-139886",
        "name": "Richard Ortíz",
        "position": "M",
        "age": 36,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-335273",
        "name": "Victor Quintana",
        "position": "M",
        "age": 23,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-270892",
        "name": "Hugo Sandoval",
        "position": "A",
        "age": 26,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-171861",
        "name": "Braian Romero",
        "position": "A",
        "age": 35,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-47086",
        "name": "Fernando Cardoso",
        "position": "A",
        "age": 25,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-350960",
        "name": "Franco Alfonso",
        "position": "A",
        "age": 24,
        "nationality": "ARG"
      }
    ]
  },
  {
    "id": "conmebol-cerro-porteno",
    "source": "ESPN par.1 roster, 2026-09-01",
    "players": [
      {
        "sourceId": "espn-256552",
        "name": "Manuel Roffo",
        "position": "G",
        "age": 26,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-378795",
        "name": "Ángel Martínez",
        "position": "G",
        "age": 24,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-119413",
        "name": "Gustavo Velázquez",
        "position": "D",
        "age": 35,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-181660",
        "name": "Iván Ramírez",
        "position": "D",
        "age": 31,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-213032",
        "name": "Guillermo Benitez",
        "position": "D",
        "age": 32,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-382860",
        "name": "Alexis Cañete",
        "position": "D",
        "age": 23,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-228577",
        "name": "Blas Riveros",
        "position": "D",
        "age": 28,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-233933",
        "name": "Lucas Merolla",
        "position": "D",
        "age": 31,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-361360",
        "name": "Ariel Gamarra",
        "position": "M",
        "age": 23,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-228565",
        "name": "Jorge Morel",
        "position": "M",
        "age": 28,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-268138",
        "name": "Derlis Rodriguez",
        "position": "M",
        "age": 28,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-224154",
        "name": "Robert Piris Da Motta",
        "position": "M",
        "age": 32,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-269799",
        "name": "Agustín Almendra",
        "position": "M",
        "age": 26,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-198728",
        "name": "Cecilio Domínguez",
        "position": "M",
        "age": 32,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-103307",
        "name": "Jonathan Torres",
        "position": "A",
        "age": 29,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-176895",
        "name": "Pablo Vegetti",
        "position": "A",
        "age": 37,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-131164",
        "name": "Carlos Franco",
        "position": "A",
        "age": 18,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-136357",
        "name": "Juan Iturbe",
        "position": "A",
        "age": 33,
        "nationality": "PAR"
      }
    ]
  },
  {
    "id": "conmebol-ldu-quito",
    "source": "ESPN ecu.1 roster, 2026-09-01",
    "players": [
      {
        "sourceId": "espn-131726",
        "name": "Gonzalo Valle",
        "position": "G",
        "age": 30,
        "nationality": "ECU"
      },
      {
        "sourceId": "espn-95614",
        "name": "Alexander Domínguez",
        "position": "G",
        "age": 39,
        "nationality": "ECU"
      },
      {
        "sourceId": "espn-358763",
        "name": "Gian Franco Allala",
        "position": "D",
        "age": 29,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-157259",
        "name": "Luis Segovia",
        "position": "D",
        "age": 28,
        "nationality": "ECU"
      },
      {
        "sourceId": "espn-188106",
        "name": "Ricardo Adé",
        "position": "D",
        "age": 36,
        "nationality": "HAI"
      },
      {
        "sourceId": "espn-269885",
        "name": "Leonel Quiñonez",
        "position": "D",
        "age": 33,
        "nationality": "ECU"
      },
      {
        "sourceId": "espn-287401",
        "name": "Richard Mina",
        "position": "D",
        "age": 27,
        "nationality": "ECU"
      },
      {
        "sourceId": "espn-215896",
        "name": "José Quintero",
        "position": "D",
        "age": 36,
        "nationality": "ECU"
      },
      {
        "sourceId": "espn-284864",
        "name": "Jesús Pretell",
        "position": "M",
        "age": 27,
        "nationality": "PER"
      },
      {
        "sourceId": "espn-358745",
        "name": "Cristian Tobar",
        "position": "M",
        "age": 26,
        "nationality": "ECU"
      },
      {
        "sourceId": "espn-283647",
        "name": "Gabriel Villamil",
        "position": "M",
        "age": 25,
        "nationality": "BOL"
      },
      {
        "sourceId": "espn-287404",
        "name": "Alexander Alvarado",
        "position": "M",
        "age": 27,
        "nationality": "ECU"
      },
      {
        "sourceId": "espn-82355",
        "name": "Fernando Cornejo",
        "position": "M",
        "age": 30,
        "nationality": "CHI"
      },
      {
        "sourceId": "espn-302230",
        "name": "José Carabali",
        "position": "M",
        "age": 29,
        "nationality": "ECU"
      },
      {
        "sourceId": "espn-192710",
        "name": "Deyverson",
        "position": "A",
        "age": 35,
        "nationality": "BRA"
      },
      {
        "sourceId": "espn-351873",
        "name": "Yerlin Quiñonez",
        "position": "A",
        "age": 25,
        "nationality": "ECU"
      },
      {
        "sourceId": "espn-251981",
        "name": "Janner Corozo",
        "position": "A",
        "age": 30,
        "nationality": "ECU"
      },
      {
        "sourceId": "espn-272499",
        "name": "Rodney Redes",
        "position": "A",
        "age": 26,
        "nationality": "PAR"
      }
    ]
  },
  {
    "id": "conmebol-barcelona-sc",
    "source": "ESPN ecu.1 roster, 2026-09-01",
    "players": [
      {
        "sourceId": "espn-165509",
        "name": "José Contreras",
        "position": "G",
        "age": 31,
        "nationality": "VEN"
      },
      {
        "sourceId": "espn-203359",
        "name": "José Cevallos",
        "position": "G",
        "age": 28,
        "nationality": "ECU"
      },
      {
        "sourceId": "espn-128008",
        "name": "Cristian Báez",
        "position": "D",
        "age": 36,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-252688",
        "name": "Bryan Carabalí",
        "position": "D",
        "age": 28,
        "nationality": "ECU"
      },
      {
        "sourceId": "espn-74966",
        "name": "Alex Rangel",
        "position": "D",
        "age": 24,
        "nationality": "ECU"
      },
      {
        "sourceId": "espn-252686",
        "name": "Gustavo Vallecilla",
        "position": "D",
        "age": 27,
        "nationality": "ECU"
      },
      {
        "sourceId": "espn-251888",
        "name": "Willian Vargas",
        "position": "D",
        "age": 29,
        "nationality": "ECU"
      },
      {
        "sourceId": "espn-228491",
        "name": "Byron Castillo",
        "position": "D",
        "age": 31,
        "nationality": "ECU"
      },
      {
        "sourceId": "espn-309395",
        "name": "Gonzalo Lugo",
        "position": "M",
        "age": 25,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-241189",
        "name": "Johnny Raul Quiñonez",
        "position": "M",
        "age": 28,
        "nationality": "ECU"
      },
      {
        "sourceId": "espn-301280",
        "name": "Jonathan Perlaza",
        "position": "M",
        "age": 25,
        "nationality": "COL"
      },
      {
        "sourceId": "espn-183011",
        "name": "Tomás Martínez",
        "position": "M",
        "age": 31,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-186304",
        "name": "Jefferson Intriago",
        "position": "M",
        "age": 30,
        "nationality": "ECU"
      },
      {
        "sourceId": "espn-381028",
        "name": "Jandry Gómez",
        "position": "M",
        "age": 20,
        "nationality": "ECU"
      },
      {
        "sourceId": "espn-189784",
        "name": "Darío Benedetto",
        "position": "A",
        "age": 36,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-176855",
        "name": "Héctor Villalba",
        "position": "A",
        "age": 32,
        "nationality": "PAR"
      },
      {
        "sourceId": "espn-387519",
        "name": "Jefferson Wila",
        "position": "A",
        "age": 20,
        "nationality": "ECU"
      },
      {
        "sourceId": "espn-129536",
        "name": "Luis Cano",
        "position": "A",
        "age": 26,
        "nationality": "ECU"
      }
    ]
  },
  {
    "id": "conmebol-atletico-nacional",
    "source": "ESPN col.1 roster, 2026-09-01",
    "players": [
      {
        "sourceId": "espn-371612",
        "name": "Simón García",
        "position": "G",
        "age": 19,
        "nationality": "ESP"
      },
      {
        "sourceId": "espn-118577",
        "name": "Franco Armani",
        "position": "G",
        "age": 39,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-252488",
        "name": "Andres Román",
        "position": "D",
        "age": 30,
        "nationality": "COL"
      },
      {
        "sourceId": "espn-135867",
        "name": "Milton Casco",
        "position": "D",
        "age": 38,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-133628",
        "name": "William Tesillo",
        "position": "D",
        "age": 36,
        "nationality": "COL"
      },
      {
        "sourceId": "espn-287250",
        "name": "César Haydar",
        "position": "D",
        "age": 25,
        "nationality": "COL"
      },
      {
        "sourceId": "espn-419252",
        "name": "Neider Parra",
        "position": "D",
        "age": 21,
        "nationality": "COL"
      },
      {
        "sourceId": "espn-407306",
        "name": "Andrés Marín",
        "position": "D",
        "age": 19,
        "nationality": "COL"
      },
      {
        "sourceId": "espn-196767",
        "name": "Edwin Cardona",
        "position": "M",
        "age": 33,
        "nationality": "COL"
      },
      {
        "sourceId": "espn-197531",
        "name": "Mateus Uribe",
        "position": "M",
        "age": 35,
        "nationality": "COL"
      },
      {
        "sourceId": "espn-270221",
        "name": "Jorman Campuzano",
        "position": "M",
        "age": 30,
        "nationality": "COL"
      },
      {
        "sourceId": "espn-287997",
        "name": "Juan Zapata",
        "position": "M",
        "age": 26,
        "nationality": "COL"
      },
      {
        "sourceId": "espn-336455",
        "name": "Samuel Velásquez",
        "position": "M",
        "age": 23,
        "nationality": "COL"
      },
      {
        "sourceId": "espn-413826",
        "name": "Matias Lozano",
        "position": "M",
        "age": 18,
        "nationality": "COL"
      },
      {
        "sourceId": "espn-70721",
        "name": "Andrés Sarmiento",
        "position": "A",
        "age": 28,
        "nationality": "COL"
      },
      {
        "sourceId": "espn-186087",
        "name": "Alfredo Morelos",
        "position": "A",
        "age": 30,
        "nationality": "COL"
      },
      {
        "sourceId": "espn-345363",
        "name": "Juan Manuel Rengifo",
        "position": "A",
        "age": 21,
        "nationality": "COL"
      },
      {
        "sourceId": "espn-197406",
        "name": "Marlos Moreno",
        "position": "A",
        "age": 29,
        "nationality": "COL"
      }
    ]
  },
  {
    "id": "conmebol-colo-colo",
    "source": "ESPN chi.1 roster, 2026-09-01",
    "players": [
      {
        "sourceId": "espn-404689",
        "name": "Gabriel Maureira",
        "position": "G",
        "age": 19,
        "nationality": "CHI"
      },
      {
        "sourceId": "espn-150072",
        "name": "Fernando de Paul",
        "position": "G",
        "age": 35,
        "nationality": "CHI"
      },
      {
        "sourceId": "espn-303323",
        "name": "Jeyson Rojas",
        "position": "D",
        "age": 24,
        "nationality": "CHI"
      },
      {
        "sourceId": "espn-335147",
        "name": "Diego Ulloa",
        "position": "D",
        "age": 23,
        "nationality": "CHI"
      },
      {
        "sourceId": "espn-292011",
        "name": "Joaquín Sosa",
        "position": "D",
        "age": 24,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-239592",
        "name": "Erick Wiemberg",
        "position": "D",
        "age": 32,
        "nationality": "CHI"
      },
      {
        "sourceId": "espn-185434",
        "name": "Matías Fernández",
        "position": "D",
        "age": 31,
        "nationality": "CHI"
      },
      {
        "sourceId": "espn-85544",
        "name": "Javier Méndez",
        "position": "D",
        "age": 31,
        "nationality": "URU"
      },
      {
        "sourceId": "espn-302163",
        "name": "Jonathan Villagra",
        "position": "M",
        "age": 25,
        "nationality": "CHI"
      },
      {
        "sourceId": "espn-252594",
        "name": "Víctor Méndez",
        "position": "M",
        "age": 26,
        "nationality": "CHI"
      },
      {
        "sourceId": "espn-202515",
        "name": "Álvaro Madrid",
        "position": "M",
        "age": 31,
        "nationality": "CHI"
      },
      {
        "sourceId": "espn-102198",
        "name": "Arturo Vidal",
        "position": "M",
        "age": 39,
        "nationality": "CHI"
      },
      {
        "sourceId": "espn-238820",
        "name": "Tomás Alarcón",
        "position": "M",
        "age": 27,
        "nationality": "CHI"
      },
      {
        "sourceId": "espn-145020",
        "name": "Claudio Aquino",
        "position": "M",
        "age": 35,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-376396",
        "name": "Leandro Hernández",
        "position": "A",
        "age": 21,
        "nationality": "CHI"
      },
      {
        "sourceId": "espn-184453",
        "name": "Maxi Romero",
        "position": "A",
        "age": 27,
        "nationality": "ARG"
      },
      {
        "sourceId": "espn-338866",
        "name": "Lautaro Pastran",
        "position": "A",
        "age": 24,
        "nationality": "CHI"
      },
      {
        "sourceId": "espn-141825",
        "name": "Marcelo Correa",
        "position": "A",
        "age": 33,
        "nationality": "ARG"
      }
    ]
  }
] as const
